services:
  3dmatchdevcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/DockerfileDevelopmentMac
    privileged: true
    tmpfs:
      - /dev/shm:size=4g  # Increased to 4GB
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0
      - CLI_JAVA_OPTS=-XX:UseSVE=0
      - JAVA_TOOL_OPTIONS=-XX:UseSVE=0
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
      - DISPLAY=docker.for.mac.host.internal:0
    ulimits:
      memlock:
        soft: -1
        hard: -1

#    volumes:
#      - ../..:/workspaces:cached
#      - ../diss:/home/tim-external/Documents/diss:cached

    # Overrides default command so things don't shut down after the process ends.
#    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: "host"
